name: workflow overview

on:
  workflow_dispatch:

jobs:
  my_self_hosted_job:
    name: my_self_hosted_job
    runs-on: ubuntu-latest

    steps:
      - name: myyamlname
        id: stepId1
        run: echo "this is smth"

      - name: another name
        id: stepId2
        shell: python
        run: |
          print("python shell is running")
